website/muzik/urls.py
from django.conf.urls import url
from . import views

app_name = 'muzik'


urlpatterns = [
	# /muzik/
    url(r'^$', views.ana_sayfa, name="ana_sayfa"),
	
	# /muzik/<album_id>/
	url(r'^(?P<album_id>[0-9]+)/$', views.detay, name="detay"),
	
	# /muzik/<album_id>/favori/
	url(r'^(?P<album_id>[0-9]+)/favori/$', views.favori, name="favori"),
	

]

website/website/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^muzik/', include('muzik.urls')),
]

website/muzik/models.py
from django.db import models

class Albumler(models.Model):
	sanatci = models.CharField(max_length=250)
	album_adi = models.CharField(max_length=250)
	album_turu = models.CharField(max_length=100)
	album_kapagi = models.CharField(max_length=1000)
	
	def __str__(self):
	    return self.album_adi + '-' + self.sanatci
	

	
	
	
class Sarkilar(models.Model):
	album = models.ForeignKey(Albumler, on_delete=models.CASCADE)
	sarki_adi = models.CharField(max_length=250)
	dosya_turu = models.CharField(max_length=10)
	favori_mi = models.BooleanField(default=False)
	
	
	
	
	
	
	
	
	
	

website/muzik/views.py
# -*- coding: utf-8 -*-
from django.http import Http404
from .models import Albumler, Sarkilar
from django.shortcuts import render, get_object_or_404

def ana_sayfa(request):
	tum_albumler = Albumler.objects.all() 
	context = {	'tum_albumler': tum_albumler,}
	return render(request, 'muzik/index.html', context)
	
	
	
def detay(request, album_id):
	# album = Albumler.objects.get(pk = album_id)
	album = get_object_or_404(Albumler, pk= album_id)
	return render(request, 'muzik/detay.html', {'album': album})
	

	
def favori(request, album_id):
	album = get_object_or_404(Albumler, pk=album_id)
	try:
		secilen_sarki = album.sarkilar_set.get(pk=request.POST['sarki'])
	except (KeyError, Sarkilar.DoesNotExist):
		return render(request, 'muzik/detay.html', {
			'album':album,
			'hata_mesaji':'Geçerli bir şarkı seçmediniz!',
			})
	else:
		if secilen_sarki.favori_mi:
			secilen_sarki.favori_mi = False
		else:
			secilen_sarki.favori_mi = True
		secilen_sarki.save()
		return render(request, 'muzik/detay.html', {'album': album})

website/muzik/templates/muzik/detay.html
<img src="{{album.album_kapagi}}">

<h1> {{album.album_adi}} </h1>
<h3> {{album.sanatci}} </h3>

<h2> Albümdeki Şarkılar: </h2>

{% if hata_mesaji %}
	<p><strong>{{ hata_mesaji}} </strong></p> 
{% endif %}	

<form action="{% url 'muzik:favori' album.id %}" method="post">
	{% csrf_token %}
	{% for siradaki in album.sarkilar_set.all %}
		<input type="radio" id="sarkilar{{ forloop.counter }}" name="sarki" value="{{siradaki.id}}"/>
		<label for="sarkilar{{ forloop.counter }}">{{ siradaki.sarki_adi}}
		{% if siradaki.favori_mi %}
		<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAclBMVEX////toQDomgD7uADwpgDtogDyqgD1rgD3sQDqnQDkkgDmlQD69e3ZzLjd1Mf4uBHw48r5z2f47dH6+PTtzp/479/x0Z758t/svXTejArqv3rwtDvgjQDklg7vwGz0z4rzx27yvkzztSbrqzX75Kn9vAD5mvbeAAAAkElEQVQYlW2NSRKEIAxFISASRFFp2wlnvf8VG0o2VPXbJPy8BEJe+p6kNE36bo1pU4GxRLkNe8z99nrbj1NKxpg5j33TxF5AucillLnIcLZeuTDjQuRCcDrrsGRnn3gyGuaBDhAppYhd/MMWAIAARRRIrVQRUHUMPs4t67o4943BME7+up7GIQZl9daqJH/4Abv4B0/mOQi4AAAAAElFTkSuQmCC">
		{% endif %}
	</label><br>	
	{% endfor %}
	<input type="submit" value="Gönder"/>
</form>

website/muzik/templates/muzik/index.html
<h1> Album Listesi </h1>
{% if tum_albumler %}
<h3>Benim tum albumlerim:</h3>
<ul>
	{% for siradaki in tum_albumler %}
	<li><a href="{% url 'muzik:detay' siradaki.id %}">{{siradaki.album_adi}}</a></li>
	{% endfor %}

</ul>
{% else %}
	<h3>Album Bulunamadi</h3>
	<h3>Suanda hicbir album bulunamamaktadir.</h3>
{% endif %}	